#!/bin/sh

# Start the first process
npm start &
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start app: $status"
  exit $status
fi

# Start the second process
/bk-api/bk-api &
status=$?
if [ $status -ne 0 ]; then
  echo "Failed to start api: $status"
  exit $status
fi

# Naive check runs checks once a minute to see if either of the processes exited.
# This illustrates part of the heavy lifting you need to do if you want to run
# more than one service in a container. The container will exit with an error
# if it detects that either of the processes has exited.
# Otherwise it will loop forever, waking up every 60 seconds
  
while /bin/true; do
  ps aux |grep 'npm' |grep -q -v grep
  BK_APP=$?
  ps aux |grep 'bk-api' |grep -q -v grep
  BK_API=$?
  # If the greps above find anything, they will exit with 0 status
  # If they are not both 0, then something is wrong
  if [ $BK_APP -ne 0 -o $BK_API -ne 0 ]; then
    echo "One of the processes has already exited."
    exit -1
  fi
  sleep 20
done
