FROM openjdk:11-jdk
RUN apt-get update -y && apt-get install -y git curl build-essential zlib1g-dev
WORKDIR /app
CMD /app/builder validate-release || exit 0 && /app/builder apply-version && /app/builder build && /app/builder upload-release
