CREATE TABLE BOOKMARK (
	IDT_BOOKMARK SERIAL PRIMARY KEY NOT NULL,
	NAM_BOOKMARK VARCHAR (500),
	DES_LINK VARCHAR (1000),
	DES_HTML TEXT,
	FLG_DELETED BOOLEAN NOT NULL,
	FLG_ARCHIVED BOOLEAN NOT NULL,
	NUM_VISIBILITY SMALLINT NOT NULL,
	DAT_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DAT_UPDATE TIMESTAMP
);
