CREATE TABLE TAG (
	IDT_TAG SERIAL PRIMARY KEY NOT NULL,
	NAM_TAG VARCHAR (100) NOT NULL,
	COD_SLUG VARCHAR (100) NOT NULL UNIQUE,
	DAT_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DAT_UPDATE TIMESTAMP NOT NULL
);
CREATE TABLE TAG_BOOKMARK (
	IDT_TAG INTEGER NOT NULL,
	IDT_BOOKMARK INTEGER NOT NULL,
	DAT_CREATION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DAT_UPDATE TIMESTAMP NOT NULL,
	PRIMARY KEY (IDT_TAG, IDT_BOOKMARK)
);

ALTER TABLE TAG_BOOKMARK
	ADD CONSTRAINT TAG_BOOKMARK_FK1
		FOREIGN KEY (IDT_TAG)
		REFERENCES TAG(IDT_TAG) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE TAG_BOOKMARK
	ADD CONSTRAINT TAG_BOOKMARK_FK2
		FOREIGN KEY (IDT_BOOKMARK)
		REFERENCES BOOKMARK(IDT_BOOKMARK) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
