INSERT INTO  SYSTEM_PROPERTY (
    NAM_PROPERTY, DES_VALUE, DAT_CREATION, DAT_UPDATE
) VALUES (
    'CODE_STYLE_TAB_SIZE', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
INSERT INTO  SYSTEM_PROPERTY (
    NAM_PROPERTY, DES_VALUE, DAT_CREATION, DAT_UPDATE
) VALUES (
    'CODE_STYLE_TAB_STYLE', 'TAB', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
