PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- RENAME TAG TABLE
ALTER TABLE tag RENAME TO tmp_tag;

CREATE TABLE TAG (
	IDT_TAG INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
	NAM_TAG VARCHAR (100) NOT NULL,
	COD_SLUG VARCHAR (100) NOT NULL UNIQUE,
	DAT_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP, 
	DAT_UPDATE DATETIME 
);

INSERT INTO TAG (IDT_TAG, NAM_TAG, COD_SLUG, DAT_CREATION)
	SELECT ID, NAME, SLUG, NULL AS DAT_CREATION
	FROM TMP_TAG;

DROP TABLE TMP_TAG;

ALTER TABLE bookmark RENAME TO tmp_bookmark;

CREATE TABLE BOOKMARK (
	IDT_BOOKMARK INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
	NAM_BOOKMARK VARCHAR (500),
	DES_LINK VARCHAR (1000),
	DES_HTML TEXT,
	FLG_DELETED BOOLEAN NOT NULL,
	FLG_ARCHIVED BOOLEAN NOT NULL,
	NUM_VISIBILITY TINYINT NOT NULL,
	DAT_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP, 
	DAT_UPDATE DATETIME 
);


INSERT INTO BOOKMARK (IDT_BOOKMARK, NAM_BOOKMARK, DES_LINK, DES_HTML, DAT_CREATION, FLG_DELETED, FLG_ARCHIVED, NUM_VISIBILITY)
	SELECT ID, NAME, LINK, HTML, NULL AS DAT_CREATION, DELETED, ARCHIVED, VISIBILITY
	FROM TMP_BOOKMARK;

DROP TABLE TMP_BOOKMARK;


CREATE TABLE TAG_BOOKMARK (
	IDT_TAG INTEGER NOT NULL REFERENCES TAG(IDT_TAG),
	IDT_BOOKMARK INTEGER NOT NULL REFERENCES BOOKMARK(IDT_BOOKMARK),
	DAT_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP, 
	DAT_UPDATE DATETIME,
	PRIMARY KEY (IDT_TAG, IDT_BOOKMARK)
);

INSERT INTO TAG_BOOKMARK (IDT_TAG, IDT_BOOKMARK, DAT_CREATION)
	SELECT TAGID, BOOKMARKID, NULL AS DAT_CREATION
	FROM tagbookmark;

DROP TABLE tagbookmark;


CREATE TABLE SYSTEM_PROPERTY (
	NAM_PROPERTY VARCHAR(25) UNIQUE NOT NULL,
	DES_VALUE VARCHAR(100),
	DAT_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP, 
	DAT_UPDATE DATETIME 
);

INSERT INTO SYSTEM_PROPERTY (NAM_PROPERTY, DES_VALUE, DAT_CREATION)
	SELECT name, value, NULL AS DAT_CREATION
	FROM SYSTEMPROPERTY;

DROP TABLE systemProperty;

UPDATE SYSTEM_PROPERTY SET DES_VALUE='1.8', DAT_UPDATE = CURRENT_TIMESTAMP WHERE NAM_PROPERTY = 'DB_VERSION';

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
