#!/bin/sh

set -e

CUR_DIR=$PWD

case $1 in

	build )

		echo "starting build"
		VERSION=`cat /VERSION`

		rm -rf $BUILD_PATH/* && \
		cd $APP_PATH && \
		go get -v github.com/golang/dep/cmd/dep && \
		dep ensure -v && \
		go test -cover=false ./.../ && \
		go build -v -o $BUILD_PATH/bk-api && \
		sh -c "cd $BUILD_PATH && tar -acvf bk-api-$VERSION.tgz *"

		echo "build success"

	;;

esac
