CREATE TABLE BOOKMARK (
	IDT_BOOKMARK INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
	NAM_BOOKMARK VARCHAR (500),
	DES_LINK VARCHAR (1000),
	DES_HTML TEXT,
	FLG_DELETED BOOLEAN NOT NULL,
	FLG_ARCHIVED BOOLEAN NOT NULL,
	NUM_VISIBILITY TINYINT NOT NULL,
	DAT_CREATION DATETIME DEFAULT CURRENT_TIMESTAMP,
	DAT_UPDATE DATETIME
);
